# Generated by Django 5.0.6 on 2024-06-27 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='especialista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('Imagen', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('Imagen', models.ImageField(upload_to='')),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='agendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('correo', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('fecha', models.DateField()),
                ('especialista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.especialista')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.servicio')),
            ],
        ),
    ]
