# Generated by Django 5.0.6 on 2024-06-27 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='informacion',
            field=models.CharField(default='Valor predeterminado', max_length=100),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='Imagen',
            field=models.ImageField(null=True, upload_to='servicios'),
        ),
    ]
