# Generated by Django 5.0.6 on 2024-07-05 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_servicio_informacion_alter_servicio_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendar',
            name='mensaje',
            field=models.CharField(default='Valor predeterminado', max_length=100),
        ),
    ]
